// =====================================================================
//  generated by ViewWeaver - first time only.
//  THIS FILE IS YOURS TO EDIT. ViewWeaver will NOT overwrite it.
//
//  source prefab : ../symbolEditor/assets/resources/spine-4.2/packs/lvbu/prefabs/lvbu-low-symbol.prefab
//  bindings base : _Lvbu_low_symbolView (in lvbu-low-symbol.gen.ts)
// =====================================================================
//
//  LvBu 低符号（A/K/Q/J/10/9）渲染器：panel + letter 组合模型。
//  - bg：共享底板，铺满设计盒（280×392）；格子适配由外层 content 等比缩放吃掉
//  - letter：字母层等比缩放居中，不裁切、不拉伸；按 symbolId 运行时换字母
//  - prefab 零脚本：本类由 SymbolView 运行时 addComponent + bind + applyLayout 注入
//  - 同一 prefab 服务全部 6 个低符号 → 资产只有 1 底板 + 6 字母

import { Node, Sprite, SpriteFrame, _decorator, resources } from "cc";
import { _Lvbu_low_symbolView } from "./lvbu-low-symbol.gen";
import type { ISymbolRenderer, SymbolRenderContext } from "../ISymbolRenderer";
import { registerSymbolRenderer } from "../SymbolRendererRegistry";
import type { IAnim } from "../../common/anim/IAnim";
import { starterAnim } from "../../common/anim/compose";
import { playVanishPlaceholder, playWinPlaceholder } from "../../editor-app/PlaceholderFx";
import type { FxHandle } from "../../editor-app/PlaceholderFx";

const { ccclass } = _decorator;

/** 字母层相对设计盒的最大占比（源资产 189/280≈0.675、237/392≈0.605） */
const LETTER_FILL_W = 0.675;
const LETTER_FILL_H = 0.605;

/** symbolId → 字母资源名（LvBu 静态导出 static/letter/letter-*.png） */
const LETTER_BY_ID: Record<number, string> = {
    8: 'A',
    9: 'K',
    10: 'Q',
    11: 'J',
    12: '10',
    13: '9',
};

const LETTER_DIR = 'spine-4.2/packs/lvbu/static/letter';

@ccclass("Lvbu_low_symbolView")
export class Lvbu_low_symbolView extends _Lvbu_low_symbolView implements ISymbolRenderer {
    private loadedLetter: string | null = null;

    applyLayout(ctx: SymbolRenderContext): void {
        // 底板铺满设计盒（外层 content 再把设计盒等比缩进实际格子）
        this.bgTransform.setContentSize(ctx.designW, ctx.designH);
        this.bg.setPosition(0, 0, 0);
        this.applyLetter(ctx);
    }

    private applyLetter(ctx: SymbolRenderContext): void {
        const name = ctx.symbolId !== null ? LETTER_BY_ID[ctx.symbolId] : undefined;
        if (!name) {
            this.layoutLetter(ctx);
            return;
        }
        if (this.loadedLetter === name) {
            this.layoutLetter(ctx);
            return;
        }
        this.loadedLetter = name;
        resources.load(`${LETTER_DIR}/letter-${name}/spriteFrame`, SpriteFrame, (err, frame) => {
            if (err || !this.isValid || this.loadedLetter !== name) return;
            this.letterSprite.spriteFrame = frame;
            this.layoutLetter(ctx);
        });
    }

    private layoutLetter(ctx: SymbolRenderContext): void {
        const frame = this.letterSprite.spriteFrame;
        if (!frame) return;
        const ow = frame.originalSize.width;
        const oh = frame.originalSize.height;
        if (!(ow > 0 && oh > 0)) return;
        // 等比缩放进「设计盒 × 占比」的窗口，不裁切不变形
        this.letterSprite.trim = false;
        this.letterSprite.sizeMode = Sprite.SizeMode.CUSTOM;
        this.letterTransform.setContentSize(ow, oh);
        const s = Math.min((ctx.designW * LETTER_FILL_W) / ow, (ctx.designH * LETTER_FILL_H) / oh);
        this.letter.setScale(s, s, 1);
        this.letter.setPosition(0, 0, 0);
    }

    // ------------------------------------------------------------------
    // 演出：临时占位（Unity 特效提取已放弃，见 lvbu/README.md）
    // 真特效就绪后替换 PlaceholderFx 的两个入口即可，本类无需改动。
    // ------------------------------------------------------------------

    /** 中奖：颜色提亮脉冲 + 轻微缩放脉冲（占位）。 */
    buildWinAnim(): IAnim | null {
        return starterAnim((finish) => {
            if (!this.isValid) {
                finish();
                return;
            }
            const handle: FxHandle = playWinPlaceholder(this.node);
            handle.done.then(finish);
            return () => handle.cancel();
        });
    }

    /** 消除：淡出 + 略微缩小（占位）。 */
    buildVanishAnim(): IAnim | null {
        return starterAnim((finish) => {
            if (!this.isValid) {
                finish();
                return;
            }
            const handle: FxHandle = playVanishPlaceholder(this.node);
            handle.done.then(finish);
            return () => handle.cancel();
        });
    }
}

// prefab 零脚本 → 由素材 id 关联 view 类（SymbolView 运行时挂载）
registerSymbolRenderer('prefab_lvbu_low', Lvbu_low_symbolView);
