// =====================================================================
//  THIS FILE IS AUTO-GENERATED by ViewWeaver. DO NOT EDIT BY HAND.
//
//  source prefab : ../symbolEditor/assets/resources/spine-4.2/packs/lvbu/prefabs/lvbu-low-symbol.prefab
//  bind config   : ../symbolEditor/assets/scripts/views/lvbu-low-symbol/lvbu-low-symbol.bind.json
//  generated at  : 2026-07-21T07:58:27.166Z
//  tool version  : 0.2.0
//
//  To change exposed nodes/components, edit the .bind.json file or use
//  the ViewWeaver editor panel, then re-run ViewWeaver.
// =====================================================================

import { Component, Node, Sprite, UITransform, _decorator } from "cc";
import type { IView } from "../IView";

/** 该 PrefabView 绑定的所有节点路径（相对根节点） */
export const NODE_PATHS = {
  bg: "bg",
  letter: "letter",
} as const;

const { ccclass } = _decorator;

/**
 * Lvbu_low_symbolView 的自动生成基类（不要直接 @ccclass 挂到节点上，请用 Lvbu_low_symbolView）。
 *
 * 字段 / bind() / onClickXxx 钩子均由 ViewWeaver 自动生成；
 * 业务逻辑请在 Lvbu_low_symbolView.ts 里 override 对应钩子。
 *
 * 实现 IView 契约 —— 编译期保证 bind(root: Node) 签名稳定，让消费侧（Presenter / Tester）
 * 不再依赖 duck typing。bind 的具体实现由 ViewWeaver 注入到下面。
 */
@ccclass("_Lvbu_low_symbolView")
export class _Lvbu_low_symbolView extends Component implements IView {
  /** 低符号底板（280x392，可 9 宫格拉伸） */
  public readonly bg!: Node;
  public readonly bgSprite!: Sprite;
  public readonly bgTransform!: UITransform;
  /** 字母层（等比缩放，不裁切） */
  public readonly letter!: Node;
  public readonly letterSprite!: Sprite;
  public readonly letterTransform!: UITransform;

  /**
   * 把运行时 prefab 实例化出的 root Node 绑定到本 View。
   * - 路径在生成期固化，运行时不做字符串拼接；
   * - 任意 path 找不到节点时，DEV 模式抛错，Release 仅 console.warn；
   * - 自动注册所有 Button / Button 子类 的 click 事件，路由到本类的 onClickXxx 钩子。
   */
  public bind(root: Node): this {
    const w = this as any;
    w.__root__ = root;
    const n_bg = root.getChildByPath("bg");
    if (!n_bg) { _viewMissing("bg"); }
    w.bg = n_bg;
    w.bgSprite = n_bg?.getComponent(Sprite);
    if (!w.bgSprite) { _viewMissing("bg::Sprite"); }
    w.bgTransform = n_bg?.getComponent(UITransform);
    if (!w.bgTransform) { _viewMissing("bg::UITransform"); }
    const n_letter = root.getChildByPath("letter");
    if (!n_letter) { _viewMissing("letter"); }
    w.letter = n_letter;
    w.letterSprite = n_letter?.getComponent(Sprite);
    if (!w.letterSprite) { _viewMissing("letter::Sprite"); }
    w.letterTransform = n_letter?.getComponent(UITransform);
    if (!w.letterTransform) { _viewMissing("letter::UITransform"); }
    return this;
  }
}

function _viewMissing(what: string): void {
  // DEV 模式下抛错，便于早暴；Release 下只警告，避免影响线上
  // eslint-disable-next-line no-undef
  const isDev = (typeof globalThis !== "undefined") && ((globalThis as any).CC_DEV || (globalThis as any).DEBUG);
  const msg = `[viewweaver] missing binding: ${what}`;
  if (isDev) { throw new Error(msg); }
  // eslint-disable-next-line no-console
  console.warn(msg);
}

export const __viewweaver_meta__ = {
  prefab: "../symbolEditor/assets/resources/spine-4.2/packs/lvbu/prefabs/lvbu-low-symbol.prefab",
  prefabName: "lvbu-low-symbol",
  totalNodes: 3,
  totalComponents: 5,
  exportedNodeCount: 2,
} as const;
